[build]
  command = "npm install && npm run build"
  publish = "dist/client"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  PUBLIC_STORE_DOMAIN = "quickstart-12345678.myshopify.com"
  PUBLIC_STOREFRONT_API_TOKEN = "dummy-token-for-build"
  PUBLIC_STOREFRONT_API_VERSION = "2024-10"
  SESSION_SECRET = "dummy-secret-for-build"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/svg/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

